export const GET_POSTS = 'GET_POSTS';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';

export const AUTHORIZATION = 'AUTHORIZATION';
export const SET_AUTHORIZATION_ERRORS = 'SET_AUTHORIZATION_ERRORS';